tap "nikitabobko/tap"
brew "aws-vault"
brew "difftastic"
brew "direnv"
brew "fzf"
brew "ripgrep"
brew "gh"
brew "git-filter-repo"
brew "git-lfs"
brew "jq"
brew "neovim"
brew "opencode"
brew "pnpm"
brew "starship"
brew "uv"
brew "zoxide"
cask "nikitabobko/tap/aerospace"
cask "git-credential-manager"
cask "ghostty"
cask "chatgpt"
cask "orbstack"
cask "raycast"
cask "tailscale"

# Work apps
cask "slack"
